### PR TITLE
./spec: add more tests for #my_inject

### PR DESCRIPTION
**Pull request by Jee-El**
## Because

This adds tests for the #my_inject method to test whether it accepts all kinds of parameters that the built-in #inject method accepts. Currently the tests cover only the case where an initial operand and a block are passed, with these new ones I added it should cover the other possible parameters.
## This PR

- Test #my_inject when it receives only a symbol
- Test #my_inject when it receives an initial value and a symbol..
- Test #my_inject when it receives only a block.
## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Hey @Jee-El 

Thanks for your PR.

We're hesitant to add this because this is already a complicated area for learners to arrive at. We aren't trying to test the exact behaviour of the Ruby core methods we're trying to mirror.

Is there a reason you feel strongly this should be added? We'd be happy to reconsider any additional information you want to provide

**Comment by Jee-El** [comment]
> Hey @Jee-El 
> 
> 
> 
> Thanks for your PR.
> 
> 
> 
> We're hesitant to add this because this is already a complicated area for learners to arrive at. We aren't trying to test the exact behaviour of the Ruby core methods we're trying to mirror.
> 
> 
> 
> Is there a reason you feel strongly this should be added? We'd be happy to reconsider any additional information you want to provide

Hello, thanks for your reply!

I thought of making this PR because the #inject method can be built cleanly using the new pattern matching that was added in ruby 3.x which was explained 1-2 lessons before this project, so trying to replicate the core #inject method seems like a good exercise to practice all kinds of pattern matching that were explained in that lesson.

I also couldn't really understand the utility of the pattern matching until I tried to use it to implement #my_inject, that was when I realized that it can make a clean and clear solution for some problems.

**Comment by Jee-El** [comment]
Maybe we could pend the more complicated tests and clarify that they don't necessarily have to pass, but if the learner is interested in taking it as a challenge, they could make them non-pending and try to get them to pass?

**Comment by CouchofTomato** [comment]
@Jee-El 

Interesting points. I'll discuss it further with the team

**Pull request closed without merging**
